### ISSUE TITLE
Timeout occurs when New message event is triggered

### ISSUE THREAD

**Issue by VaishnaviNaik96** [psvkaushik/CSC-510-Project2-TeachersPetBotv2.0#17]

**Comment by ayush-ai8** [comment]
The Timeout was an extra condition and the same has been removed.
Thanks for catching the corner case.

**Comment by VaishnaviNaik96** [comment]
The resolution looks fine. Thanks

**Comment by ayush-ai8** [comment]
thanks for the confirmation, closing the issue.
