### ISSUE TITLE
Respost is Not Displaying correctly

### ISSUE THREAD

**Issue by psvkaushik** [psvkaushik/CSC-510-Project2-TeachersPetBotv2.0#27]

**Comment by VaishnaviNaik96** [comment]
Thanks for pointing that out! Let me check and get back to you

**Comment by VaishnaviNaik96** [comment]
I have resolved the issue. Could you please confirm the same?

**Comment by psvkaushik** [comment]
Yes it is displaying it properly

**Comment by VaishnaviNaik96** [comment]
Great! Thank you for confirming. Will close the issue.
